const subrgyPBHNG = [
  { id: 1, ubrgy:  'A.DelRosario Street'},
  { id: 2, ubrgy:  'A.Perez Street'},
  { id: 3, ubrgy:  'Bangka Bangka'},
  { id: 4, ubrgy:  'Bypass Road'},
  { id: 5, ubrgy:  'City Land Drive'},
  { id: 6, ubrgy:  'C.DelRosario Street'},
  { id: 7, ubrgy:  'E.Hermogenes Street'},
  { id: 8, ubrgy:  'E.Nicolas Street'},
  { id: 9, ubrgy:  'F.Buenavista Street'},
  { id: 10, ubrgy:  'F.Glorioso Street'},
  { id: 11, ubrgy: 'Garden Village Phase 1'},
  { id: 12, ubrgy: 'Garden Village Phase 2'},
  { id: 13, ubrgy: 'Garden Village Phase 3'},
  { id: 14, ubrgy: 'Garden Village Phase 4'},
  { id: 15, ubrgy: 'Garden Village phase 5'},
  { id: 16, ubrgy: 'Gulod Road'},
  { id: 17, ubrgy: 'G.P,Reyes Street'},
  { id: 18, ubrgy: 'Km37'},
  { id: 19, ubrgy: 'Km38'},
  { id: 20, ubrgy: 'L.Angeles Street'},
  { id: 21, ubrgy: 'L.Fausto Street'},
  { id: 22, ubrgy: 'M.Fausto Street'},
  { id: 23, ubrgy: 'Maligaya Street'},
  { id: 24, ubrgy: 'Maningas Street'},
  { id: 25, ubrgy: 'Milagrosa Street'},
  { id: 26, ubrgy: 'Muskoka Ville'},
  { id: 27, ubrgy: 'Nepo Homes'},
  { id: 28, ubrgy: 'Perez'},
  { id: 29, ubrgy: 'P.Gubala Street'},
  { id: 30, ubrgy: 'Redwood Residence'},
  { id: 31, ubrgy: 'Route 39'},
  { id: 32, ubrgy: 'Sitio Diliman Road'},
  { id: 33, ubrgy: 'Sitio Manggahan Street'},
  { id: 34, ubrgy: 'Sulucan Perez'},
  { id: 35, ubrgy: 'Tierra De StaMaria Phase 1'},
  { id: 36, ubrgy: 'Tierra De StaMaria Phase 2'},
  { id: 37, ubrgy: 'Tierra De StaMaria Phase 3'},
  { id: 38, ubrgy: 'Tierra De StaMaria Phase 4'},
  { id: 39, ubrgy: 'Tierra De StaMaria Phase 5'}
];

export default subrgyPBHNG;