const subrgyPBHNG = [
  { id: 1, ubrgy:  'A.DelRosarioStreet'},
  { id: 2, ubrgy:  'A.PerezStreet'},
  { id: 3, ubrgy:  'BangkaBangka'},
  { id: 3, ubrgy:  'BypassRoad'},
  { id: 4, ubrgy:  'CityLandDrive'},
  { id: 5, ubrgy:  'C.DelRosarioStreet'},
  { id: 6, ubrgy:  'E.HermogenesStreet'},
  { id: 7, ubrgy:  'E.NicolasStreet'},
  { id: 8, ubrgy:  'F.BuenavistaStreet'},
  { id: 9, ubrgy:  'F.GloriosoStreet'},
  { id: 10, ubrgy: 'GardenVillage'},
  { id: 11, ubrgy: 'Phase1'},
  { id: 12, ubrgy: 'Phase2'},
  { id: 13, ubrgy: 'Phase3'},
  { id: 14, ubrgy: 'Phase4'},
  { id: 15, ubrgy: 'phase5'},
  { id: 16, ubrgy: 'GulodRoad'},
  { id: 17, ubrgy: 'G.P,ReyesStreet'},
  { id: 18, ubrgy: 'Km37'},
  { id: 19, ubrgy: 'Km38'},
  { id: 20, ubrgy: 'L.AngelesStreet'},
  { id: 21, ubrgy: 'L.FaustoStreet'},
  { id: 22, ubrgy: 'M.FaustoStreet'},
  { id: 23, ubrgy: 'MagasawangSapaRoad'},
  { id: 24, ubrgy: 'MaligayaStreet'},
  { id: 25, ubrgy: 'ManingasStreet'},
  { id: 26, ubrgy: 'MilagrosaStreet'},
  { id: 27, ubrgy: 'MuskokaVille'},
  { id: 28, ubrgy: 'NepoHomesPhase1'},
  { id: 29, ubrgy: 'NepoHomesPhase2'},
  { id: 30, ubrgy: 'Perez'},
  { id: 31, ubrgy: 'P.GubalaStreet'},
  { id: 32, ubrgy: 'PulongBuhanginBalasingCatmonRoad'},
  { id: 33, ubrgy: 'RedwoodResidence'},
  { id: 34, ubrgy: 'Route39'},
  { id: 35, ubrgy: 'SitioDilimanRoad'},
  { id: 36, ubrgy: 'SitioManggahanStreet'},
  { id: 37, ubrgy: 'SulucanPerez'},
  { id: 38, ubrgy: 'TierraDeStaMaria'},
  { id: 39, ubrgy: 'TierraDeStaMariaPhase1'},
  { id: 40, ubrgy: 'TierraDeStaMariaPhase2'},
  { id: 41, ubrgy: 'TierraDeStaMariaPhase3'},
  { id: 42, ubrgy: 'TierraDeStaMariaPhase4'},
  { id: 43, ubrgy: 'TierraDeStaMariaPhase5'}
];

export default subrgyPBHNG;