const subrgyPBHNG = [
  { id: 1, ubrgy:  'A.DelRosario Street', SFee:'Free'},
  { id: 2, ubrgy:  'A.Perez Street', SFee:'Free'},
  { id: 3, ubrgy:  'Bangka Bangka', SFee:"35"},
  { id: 4, ubrgy:  'Bypass Road', SFee:'Free'},
  { id: 5, ubrgy:  'City Land Drive', SFee:'Free'},
  { id: 6, ubrgy:  'C.DelRosario Street', SFee:'Free'},
  { id: 7, ubrgy:  'E.Hermogenes Street', SFee:'Free'},
  { id: 8, ubrgy:  'E.Nicolas Street', SFee:'Free'},
  { id: 9, ubrgy:  'F.Buenavista Street', SFee:"35"},
  { id: 10, ubrgy:  'F.Glorioso Street', SFee:"35"},
  { id: 11, ubrgy: 'Garden Village Phase 1', SFee:"45"},
  { id: 12, ubrgy: 'Garden Village Phase 2', SFee:"45"},
  { id: 13, ubrgy: 'Garden Village Phase 3', SFee:"45"},
  { id: 14, ubrgy: 'Garden Village Phase 4', SFee:"45"},
  { id: 15, ubrgy: 'Garden Village phase 5', SFee:"45"},
  { id: 16, ubrgy: 'Gulod Road', SFee:"Free"},
  { id: 17, ubrgy: 'G.P,Reyes Street', SFee:"35"},
  { id: 18, ubrgy: 'Km37', SFee:"35"},
  { id: 19, ubrgy: 'Km38', SFee:"35"},
  { id: 20, ubrgy: 'L.Angeles Street', SFee:"Free"},
  { id: 21, ubrgy: 'L.Fausto Street', SFee:"35"},
  { id: 22, ubrgy: 'M.Fausto Street', SFee:"35"},
  { id: 23, ubrgy: 'Maligaya Street', SFee:"1000"},
  { id: 24, ubrgy: 'Maningas Street', SFee:"Free"},
  { id: 25, ubrgy: 'Milagrosa Street', SFee:"Free"},
  { id: 26, ubrgy: 'Muskoka Ville', SFee:"35"},
  { id: 27, ubrgy: 'Nepo Homes', SFee:"35"},
  { id: 28, ubrgy: 'Perez', SFee:"45"},
  { id: 29, ubrgy: 'P.Gubala Street', SFee:"1000"},
  { id: 30, ubrgy: 'Redwood Residence', SFee:"35"},
  { id: 31, ubrgy: 'Route 39', SFee:"45"},
  { id: 32, ubrgy: 'Sitio Diliman Road', SFee:"65"},
  { id: 33, ubrgy: 'Sitio Manggahan Street', SFee:"45"},
  { id: 34, ubrgy: 'Sulucan Perez', SFee:"45"},
  { id: 35, ubrgy: 'Tierra De StaMaria Phase 1', SFee:"35"},
  { id: 36, ubrgy: 'Tierra De StaMaria Phase 2', SFee:"35"},
  { id: 37, ubrgy: 'Tierra De StaMaria Phase 3', SFee:"35"},
  { id: 38, ubrgy: 'Tierra De StaMaria Phase 4', SFee:"35"},
  { id: 39, ubrgy: 'Tierra De StaMaria Phase 5', SFee:"35"}
];

export default subrgyPBHNG;