<template>
  <div>
    <v-app-bar
      color="#FFFFFF"
      height="auto"
    >
      <v-container fluid>
        <v-row>
          <v-col
            cols="12"
          >
            <div
              class="d-flex"
            >
              <router-link
                to="/"
              >
                <v-img
                  contain
                  src="../../assets/ERICH.svg"
                  max-height="120x"
                  max-width="120px"
                  class="mr-1"
                ></v-img>
              </router-link>
              <v-divider
                vertical
              ></v-divider>
              <p
                class="text-h5 ml-3 pt-1 my-0 grey--text text--darken-1"
              >About</p>
            </div>
          </v-col>
        </v-row>
      </v-container>
    </v-app-bar>
  </div>
</template>
