const sbrgy = [
  { id: 1, brgy: 'Bagbaguin', brgyCond: 'smbBagBaguin'},
  { id: 2, brgy: 'Balasing', brgyCond: 'smbBalasing'},
  { id: 3, brgy: 'Bulac', brgyCond: 'smbBulac'},
  { id: 4, brgy: 'Camangyan', brgyCond: 'smbCamangyan'},
  { id: 5, brgy: 'Catmon', brgyCond: 'smbCatmon'},
  { id: 6, brgy: 'Caypombo', brgyCond: 'smbCaypombo'},
  { id: 7, brgy: 'Caysio', brgyCond: 'smbCaysio'},
  { id: 8, brgy: 'Guyong', brgyCond: 'smbGuyong'},
  { id: 9, brgy: 'Lalakhan', brgyCond: 'smblalakhan'},
  { id: 10, brgy: 'Mag-Asawang Sapa', brgyCond: 'smbMagAsawangSapa'},
  { id: 11, brgy: 'Manggahan', brgyCond: 'smbManggahan'},
  { id: 12, brgy: 'Parada', brgyCond: 'smbParada'},
  { id: 13, brgy: 'Poblacion', brgyCond: 'smbPoblacion'},
  { id: 14, brgy: 'Pulong Buhangin', brgyCond: 'smbPulongBuhangin'},
  { id: 15, brgy: 'San JosePatag', brgyCond: 'smbSanJosePatag'},
  { id: 16, brgy: 'Santa Clara', brgyCond: 'smbSantaClara'},
  { id: 17, brgy: 'Santa Cruz', brgyCond: 'smbStaCruz'},
  // { id: 1, brgy: 'Bagbaguin', brgyCond: 'smbBagBaguin'},
  // { id: 2, brgy: 'Balasing', brgyCond: 'smbBalasing'},
  // { id: 3, brgy: 'Buenavista', brgyCond: 'smbBuenavista'},
  // { id: 4, brgy: 'Bulac', brgyCond: 'smbBulac'},
  // { id: 5, brgy: 'Camangyan', brgyCond: 'smbCamangyan'},
  // { id: 6, brgy: 'Catmon', brgyCond: 'smbCatmon'},
  // { id: 7, brgy: 'Caypombo', brgyCond: 'smbCaypombo'},
  // { id: 8, brgy: 'Caysio', brgyCond: 'smbCaysio'},
  // { id: 9, brgy: 'Guyong', brgyCond: 'smbGuyong'},
  // { id: 10, brgy: 'Lalakhan', brgyCond: 'smblalakhan'},
  // { id: 11, brgy: 'Mag-Asawang Sapa', brgyCond: 'smbMagAsawangSapa'},
  // { id: 12, brgy: 'Mahabang Parang', brgyCond: 'smbMahabangParang'},
  // { id: 13, brgy: 'Manggahan', brgyCond: 'smbManggahan'},
  // { id: 14, brgy: 'Parada', brgyCond: 'smbParada'},
  // { id: 15, brgy: 'Poblacion', brgyCond: 'smbPoblacion'},
  // { id: 16, brgy: 'Pulong Buhangin', brgyCond: 'smbPulongBuhangin'},
  // { id: 17, brgy: 'San Gabriel', brgyCond: 'smbSanGabriel'},
  // { id: 18, brgy: 'San JosePatag', brgyCond: 'smbSanJosePatag'},
  // { id: 19, brgy: 'Santa Clara', brgyCond: 'smbSantaClara'},
  // { id: 20, brgy: 'San Vicente', brgyCond: 'smbSanVicente'},
  // { id: 21, brgy: 'Santa Cruz', brgyCond: 'smbStaCruz'},
  // { id: 22, brgy: 'Silangan', brgyCond: 'smbSilangan'},
  // { id: 23, brgy: 'Tabing Bakod', brgyCond: 'smbTabingBakod'},
  // { id: 24, brgy: 'Tumana', brgyCond: 'smbTumana'},
];

export default sbrgy;
